### ISSUE TITLE
Delta Analysis Follow-up

### ISSUE THREAD

**Issue by SimonTopp** [GlobalHydrologyLab/DeltaSynchronicity#3]
@ebgoldstein Looks like some of the GRDC off-set work you did wasn't included with what I pushed up.  You should be able to restore it from 046df53d74f15c32ee7884a77990c2b4b8d2f84b  .   I'd do it, but seems like too many cooks in the kitchen.

**Comment by ebgoldstein** [comment]
i think this is fixed... added via https://github.com/GlobalHydrologyLab/DeltaSynchronicity/commit/34866bd89458d4cb623415e3ad964f8c2a74648b
