### ISSUE TITLE
Delta Analysis Follow-Up

### ISSUE THREAD

**Issue by SimonTopp** [GlobalHydrologyLab/DeltaSynchronicity#4]
@ebgoldstein Looks like some of the GRDC off-set work you did wasn't included with what I pushed up.  You should be able to restore it from 046df53d74f15c32ee7884a77990c2b4b8d2f84b  .   I'd do it, but seems like too many cooks in the kitchen.

**Comment by ebgoldstein** [comment]
ok — thx for the check — i will likely cut and paste the relevant parts from https://github.com/GlobalHydrologyLab/DeltaSynchronicity/commit/046df53d74f15c32ee7884a77990c2b4b8d2f84b

**Comment by ebgoldstein** [comment]
i think this is fixed... GRIDC analysis added via 34866bd... whew...
